//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentDirectory.com
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Address()
        {
            this.StudentTables = new HashSet<StudentTable>();
        }
    
        public int AddressID { get; set; }
        public string BuildingNo { get; set; }
        public int CityID { get; set; }
        public int PostcodeID { get; set; }
        public Nullable<int> CountyID { get; set; }
    
        public virtual Cities City { get; set; }
        public virtual Counties County { get; set; }
        public virtual Postcodes Postcode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentTable> StudentTables { get; set; }
    }
}
