//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentDirectory.com
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentTable
    {
        public int StudentID { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string DateOfBirth { get; set; }
        public int AddressID { get; set; }
        public int ID { get; set; }
        public int ClassID { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Classes Class { get; set; }
        public virtual Univeristytable Univeristytable { get; set; }
    }
}
